version: '3.8'

networks:
  mcpnetwork:
    external: true

services:
  ecommerce_loader:
    build: .
    container_name: ecommerce_loader
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8002:8002"
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8002   # ou troque para o comando uvicorn se precisar
